version: "3.8"

services:
  restaurante-app:
    image: ghcr.io/wiliansil/restaurante-app:latest
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "212.85.17.139"
      DB_PORT: "5432"
      DB_NAME: "restaurante"
      DB_USER: "postgres"
      DB_PASSWORD: "postgreshml"
      PORT: "3000"
      N8N_WEBHOOK_URL: "https://hook.feedconnect.com.br/webhook-test/comanda-finalizada"
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "admin123456"
      SESSION_SECRET: "superadmin123456"
    restart: unless-stopped